services:
- type: web
  name: line-bot-python-flask
  env: python
  repo: https://github.com/acs106104/Flask-LINE-Bot-Heroku.git
  buildCommand: pip install gunicorn -r requirements.txt
  startCommand: gunicorn app:app
  plan: free
  autoDeploy: false
  envVars:
  - key: LINE_CHANNEL_ACCESS_TOKEN
    sync: false
  - key: LINE_CHANNEL_SECRET
    sync: false